#!/usr/bin/env bash
# chrome-debug.sh — launch the dedicated "Job Applications" Chrome instance.
#
# This instance is completely separate from any other Chrome debug session you
# may be running (e.g. the MCP/Leonardo.Ai session on port 9222). It uses its
# own profile directory (~/.chrome-apply-profile) and its own remote-debug port
# (9223), so the two never interfere.
#
# The window is themed PURPLE via --install-autogenerated-theme so it is
# visually unmistakeable from your regular Chrome windows.
#
# First run: the profile directory is empty (fresh Chrome install). Log into
# job-application sites once in this window — LinkedIn, Greenhouse, Ashby,
# Lever, Workday — and those sessions will persist here automatically.

PORT=9223
# Dedicated profile for job-application automation. Fresh dir, never shared
# with other automation sessions or regular browsing.
PROFILE_DIR="$HOME/.chrome-apply-profile"
CHROME_BIN="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

# Check if something is already listening on the port — if so, we're good.
if lsof -iTCP:"$PORT" -sTCP:LISTEN -t &>/dev/null; then
  echo "Job Applications Chrome already running on port $PORT — nothing to do."
  echo "If you need a fresh session: quit that purple Chrome window and re-run this script."
  exit 0
fi

# Create the profile dir if it's the first run.
if [ ! -d "$PROFILE_DIR" ]; then
  mkdir -p "$PROFILE_DIR"
  echo "Created dedicated Job Applications Chrome profile at $PROFILE_DIR"
fi

# Seed a Preferences file with the profile name on first run. Chrome's avatar
# button (top-right) will show "Job Applications", making the window easy to
# identify even before the purple theme is applied.
if [ ! -f "$PROFILE_DIR/Default/Preferences" ]; then
  mkdir -p "$PROFILE_DIR/Default"
  printf '{"profile":{"name":"Job Applications"}}' > "$PROFILE_DIR/Default/Preferences"
  echo ""
  echo "FIRST-RUN SETUP:"
  echo "  This is a brand-new Chrome profile — your other Chrome sessions are untouched."
  echo "  Log into job-application sites once (LinkedIn, Greenhouse, Ashby, Lever,"
  echo "  Workday) in this purple window — those sessions will persist here automatically."
fi

echo "Launching Job Applications Chrome on port $PORT (profile: $PROFILE_DIR) ..."
"$CHROME_BIN" \
  --remote-debugging-port="$PORT" \
  --user-data-dir="$PROFILE_DIR" \
  --no-first-run \
  --no-default-browser-check \
  --install-autogenerated-theme=124,77,255 \
  &>/dev/null &

# Wait up to 5s for the debug port to open.
for i in $(seq 1 10); do
  if lsof -iTCP:"$PORT" -sTCP:LISTEN -t &>/dev/null; then
    echo "Job Applications Chrome is ready — remote debug on port $PORT."
    exit 0
  fi
  sleep 0.5
done

echo "Warning: Chrome launched but port $PORT is not responding yet."
echo "Wait a moment, then run: curl -s http://127.0.0.1:$PORT/json/version"
exit 1
